// flow-typed signature: 553e36e888eaf2d1e7284c2509889c2d
// flow-typed version: <<STUB>>/aurelia-event-aggregator_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aurelia-event-aggregator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'aurelia-event-aggregator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aurelia-event-aggregator/build/args' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/babel-options' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/paths' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/build' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/clean' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/dev' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/doc' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/lint' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/prepare-release' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/tasks/test' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/build/typescript-options' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/config' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/amd/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/amd/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/commonjs/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/es2015/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/es2015/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/native-modules/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/native-modules/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/system/aurelia-event-aggregator' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/dist/system/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/gulpfile' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/karma.conf' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/src/index' {
  declare module.exports: any;
}

declare module 'aurelia-event-aggregator/test/event-aggregator.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aurelia-event-aggregator/build/args.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/args'>;
}
declare module 'aurelia-event-aggregator/build/babel-options.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/babel-options'>;
}
declare module 'aurelia-event-aggregator/build/paths.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/paths'>;
}
declare module 'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/prettify'>;
}
declare module 'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/reports/coverage/Chrome 43.0.2357 (Mac OS X 10.10.3)/sorter'>;
}
declare module 'aurelia-event-aggregator/build/tasks/build.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/build'>;
}
declare module 'aurelia-event-aggregator/build/tasks/clean.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/clean'>;
}
declare module 'aurelia-event-aggregator/build/tasks/dev.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/dev'>;
}
declare module 'aurelia-event-aggregator/build/tasks/doc.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/doc'>;
}
declare module 'aurelia-event-aggregator/build/tasks/lint.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/lint'>;
}
declare module 'aurelia-event-aggregator/build/tasks/prepare-release.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/prepare-release'>;
}
declare module 'aurelia-event-aggregator/build/tasks/test.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/tasks/test'>;
}
declare module 'aurelia-event-aggregator/build/typescript-options.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/build/typescript-options'>;
}
declare module 'aurelia-event-aggregator/config.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/config'>;
}
declare module 'aurelia-event-aggregator/dist/amd/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/amd/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/amd/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/amd/index'>;
}
declare module 'aurelia-event-aggregator/dist/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/commonjs/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/commonjs/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/commonjs/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/commonjs/index'>;
}
declare module 'aurelia-event-aggregator/dist/es2015/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/es2015/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/es2015/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/es2015/index'>;
}
declare module 'aurelia-event-aggregator/dist/native-modules/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/native-modules/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/native-modules/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/native-modules/index'>;
}
declare module 'aurelia-event-aggregator/dist/system/aurelia-event-aggregator.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/system/aurelia-event-aggregator'>;
}
declare module 'aurelia-event-aggregator/dist/system/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/dist/system/index'>;
}
declare module 'aurelia-event-aggregator/gulpfile.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/gulpfile'>;
}
declare module 'aurelia-event-aggregator/karma.conf.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/karma.conf'>;
}
declare module 'aurelia-event-aggregator/src/index.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/src/index'>;
}
declare module 'aurelia-event-aggregator/test/event-aggregator.spec.js' {
  declare module.exports: $Exports<'aurelia-event-aggregator/test/event-aggregator.spec'>;
}
