// flow-typed signature: 10af53ee3079a276e16a48858716f7ad
// flow-typed version: <<STUB>>/mainloop.js_v^1.0.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mainloop.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mainloop.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mainloop.js/build/mainloop.min' {
  declare module.exports: any;
}

declare module 'mainloop.js/docs/app-a7074955bb2a89176f917b889c161b94' {
  declare module.exports: any;
}

declare module 'mainloop.js/docs/data-c60451f2ada51cc581014c9f68c98df4' {
  declare module.exports: any;
}

declare module 'mainloop.js/docs/extjs/ext-all' {
  declare module.exports: any;
}

declare module 'mainloop.js/docs/output/MainLoop' {
  declare module.exports: any;
}

declare module 'mainloop.js/docs/resources/prettify/prettify' {
  declare module.exports: any;
}

declare module 'mainloop.js/Gruntfile' {
  declare module.exports: any;
}

declare module 'mainloop.js/src/mainloop' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mainloop.js/build/mainloop.min.js' {
  declare module.exports: $Exports<'mainloop.js/build/mainloop.min'>;
}
declare module 'mainloop.js/docs/app-a7074955bb2a89176f917b889c161b94.js' {
  declare module.exports: $Exports<'mainloop.js/docs/app-a7074955bb2a89176f917b889c161b94'>;
}
declare module 'mainloop.js/docs/data-c60451f2ada51cc581014c9f68c98df4.js' {
  declare module.exports: $Exports<'mainloop.js/docs/data-c60451f2ada51cc581014c9f68c98df4'>;
}
declare module 'mainloop.js/docs/extjs/ext-all.js' {
  declare module.exports: $Exports<'mainloop.js/docs/extjs/ext-all'>;
}
declare module 'mainloop.js/docs/output/MainLoop.js' {
  declare module.exports: $Exports<'mainloop.js/docs/output/MainLoop'>;
}
declare module 'mainloop.js/docs/resources/prettify/prettify.js' {
  declare module.exports: $Exports<'mainloop.js/docs/resources/prettify/prettify'>;
}
declare module 'mainloop.js/Gruntfile.js' {
  declare module.exports: $Exports<'mainloop.js/Gruntfile'>;
}
declare module 'mainloop.js/src/mainloop.js' {
  declare module.exports: $Exports<'mainloop.js/src/mainloop'>;
}
