// flow-typed signature: a0941958d41365e0702319db6449aac5
// flow-typed version: <<STUB>>/peerjs_v^0.3.14/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'peerjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'peerjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'peerjs/dist/peer' {
  declare module.exports: any;
}

declare module 'peerjs/dist/peer.min' {
  declare module.exports: any;
}

declare module 'peerjs/docs/build' {
  declare module.exports: any;
}

declare module 'peerjs/docs/index' {
  declare module.exports: any;
}

declare module 'peerjs/Gruntfile' {
  declare module.exports: any;
}

declare module 'peerjs/lib/adapter' {
  declare module.exports: any;
}

declare module 'peerjs/lib/dataconnection' {
  declare module.exports: any;
}

declare module 'peerjs/lib/exports' {
  declare module.exports: any;
}

declare module 'peerjs/lib/mediaconnection' {
  declare module.exports: any;
}

declare module 'peerjs/lib/negotiator' {
  declare module.exports: any;
}

declare module 'peerjs/lib/peer' {
  declare module.exports: any;
}

declare module 'peerjs/lib/socket' {
  declare module.exports: any;
}

declare module 'peerjs/lib/util' {
  declare module.exports: any;
}

declare module 'peerjs/test/adapter' {
  declare module.exports: any;
}

declare module 'peerjs/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'peerjs/dist/peer.js' {
  declare module.exports: $Exports<'peerjs/dist/peer'>;
}
declare module 'peerjs/dist/peer.min.js' {
  declare module.exports: $Exports<'peerjs/dist/peer.min'>;
}
declare module 'peerjs/docs/build.js' {
  declare module.exports: $Exports<'peerjs/docs/build'>;
}
declare module 'peerjs/docs/index.js' {
  declare module.exports: $Exports<'peerjs/docs/index'>;
}
declare module 'peerjs/Gruntfile.js' {
  declare module.exports: $Exports<'peerjs/Gruntfile'>;
}
declare module 'peerjs/lib/adapter.js' {
  declare module.exports: $Exports<'peerjs/lib/adapter'>;
}
declare module 'peerjs/lib/dataconnection.js' {
  declare module.exports: $Exports<'peerjs/lib/dataconnection'>;
}
declare module 'peerjs/lib/exports.js' {
  declare module.exports: $Exports<'peerjs/lib/exports'>;
}
declare module 'peerjs/lib/mediaconnection.js' {
  declare module.exports: $Exports<'peerjs/lib/mediaconnection'>;
}
declare module 'peerjs/lib/negotiator.js' {
  declare module.exports: $Exports<'peerjs/lib/negotiator'>;
}
declare module 'peerjs/lib/peer.js' {
  declare module.exports: $Exports<'peerjs/lib/peer'>;
}
declare module 'peerjs/lib/socket.js' {
  declare module.exports: $Exports<'peerjs/lib/socket'>;
}
declare module 'peerjs/lib/util.js' {
  declare module.exports: $Exports<'peerjs/lib/util'>;
}
declare module 'peerjs/test/adapter.js' {
  declare module.exports: $Exports<'peerjs/test/adapter'>;
}
declare module 'peerjs/test/util.js' {
  declare module.exports: $Exports<'peerjs/test/util'>;
}
